spring:
  application:
    name: taco-cloud
  datasource:
    generate-unique-name: false
    name: tacocloud
  jpa:
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      mode: never     # файл data.sql больше не используется

taco:
  orders:
    pageSize: 10