spring:
  application:
    name: taco-cloud
  datasource:
    generate-unique-name: false
    name: tacocloud
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true   # data.sql ПОСЛЕ Hibernate
  sql:
    init:
      mode: always
